/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CloudAccountListerExpansion allows custom methods to be added to
// CloudAccountLister.
type CloudAccountListerExpansion interface{}

// CloudAccountNamespaceListerExpansion allows custom methods to be added to
// CloudAccountNamespaceLister.
type CloudAccountNamespaceListerExpansion interface{}

// SubscriptionListerExpansion allows custom methods to be added to
// SubscriptionLister.
type SubscriptionListerExpansion interface{}

// SubscriptionNamespaceListerExpansion allows custom methods to be added to
// SubscriptionNamespaceLister.
type SubscriptionNamespaceListerExpansion interface{}

// SubscriptionPeeringListerExpansion allows custom methods to be added to
// SubscriptionPeeringLister.
type SubscriptionPeeringListerExpansion interface{}

// SubscriptionPeeringNamespaceListerExpansion allows custom methods to be added to
// SubscriptionPeeringNamespaceLister.
type SubscriptionPeeringNamespaceListerExpansion interface{}
