/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-rediscloud-api/apis/rediscloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCloudAccounts implements CloudAccountInterface
type FakeCloudAccounts struct {
	Fake *FakeRediscloudV1alpha1
	ns   string
}

var cloudaccountsResource = schema.GroupVersionResource{Group: "rediscloud.rediscloud.kubeform.com", Version: "v1alpha1", Resource: "cloudaccounts"}

var cloudaccountsKind = schema.GroupVersionKind{Group: "rediscloud.rediscloud.kubeform.com", Version: "v1alpha1", Kind: "CloudAccount"}

// Get takes name of the cloudAccount, and returns the corresponding cloudAccount object, and an error if there is any.
func (c *FakeCloudAccounts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CloudAccount, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cloudaccountsResource, c.ns, name), &v1alpha1.CloudAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudAccount), err
}

// List takes label and field selectors, and returns the list of CloudAccounts that match those selectors.
func (c *FakeCloudAccounts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CloudAccountList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cloudaccountsResource, cloudaccountsKind, c.ns, opts), &v1alpha1.CloudAccountList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CloudAccountList{ListMeta: obj.(*v1alpha1.CloudAccountList).ListMeta}
	for _, item := range obj.(*v1alpha1.CloudAccountList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cloudAccounts.
func (c *FakeCloudAccounts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cloudaccountsResource, c.ns, opts))

}

// Create takes the representation of a cloudAccount and creates it.  Returns the server's representation of the cloudAccount, and an error, if there is any.
func (c *FakeCloudAccounts) Create(ctx context.Context, cloudAccount *v1alpha1.CloudAccount, opts v1.CreateOptions) (result *v1alpha1.CloudAccount, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cloudaccountsResource, c.ns, cloudAccount), &v1alpha1.CloudAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudAccount), err
}

// Update takes the representation of a cloudAccount and updates it. Returns the server's representation of the cloudAccount, and an error, if there is any.
func (c *FakeCloudAccounts) Update(ctx context.Context, cloudAccount *v1alpha1.CloudAccount, opts v1.UpdateOptions) (result *v1alpha1.CloudAccount, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cloudaccountsResource, c.ns, cloudAccount), &v1alpha1.CloudAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudAccount), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCloudAccounts) UpdateStatus(ctx context.Context, cloudAccount *v1alpha1.CloudAccount, opts v1.UpdateOptions) (*v1alpha1.CloudAccount, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cloudaccountsResource, "status", c.ns, cloudAccount), &v1alpha1.CloudAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudAccount), err
}

// Delete takes name of the cloudAccount and deletes it. Returns an error if one occurs.
func (c *FakeCloudAccounts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cloudaccountsResource, c.ns, name), &v1alpha1.CloudAccount{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCloudAccounts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cloudaccountsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CloudAccountList{})
	return err
}

// Patch applies the patch and returns the patched cloudAccount.
func (c *FakeCloudAccounts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CloudAccount, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cloudaccountsResource, c.ns, name, pt, data, subresources...), &v1alpha1.CloudAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudAccount), err
}
