/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-rediscloud-api/apis/subscription/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePeerings implements PeeringInterface
type FakePeerings struct {
	Fake *FakeSubscriptionV1alpha1
	ns   string
}

var peeringsResource = schema.GroupVersionResource{Group: "subscription.rediscloud.kubeform.com", Version: "v1alpha1", Resource: "peerings"}

var peeringsKind = schema.GroupVersionKind{Group: "subscription.rediscloud.kubeform.com", Version: "v1alpha1", Kind: "Peering"}

// Get takes name of the peering, and returns the corresponding peering object, and an error if there is any.
func (c *FakePeerings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Peering, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(peeringsResource, c.ns, name), &v1alpha1.Peering{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Peering), err
}

// List takes label and field selectors, and returns the list of Peerings that match those selectors.
func (c *FakePeerings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PeeringList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(peeringsResource, peeringsKind, c.ns, opts), &v1alpha1.PeeringList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PeeringList{ListMeta: obj.(*v1alpha1.PeeringList).ListMeta}
	for _, item := range obj.(*v1alpha1.PeeringList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested peerings.
func (c *FakePeerings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(peeringsResource, c.ns, opts))

}

// Create takes the representation of a peering and creates it.  Returns the server's representation of the peering, and an error, if there is any.
func (c *FakePeerings) Create(ctx context.Context, peering *v1alpha1.Peering, opts v1.CreateOptions) (result *v1alpha1.Peering, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(peeringsResource, c.ns, peering), &v1alpha1.Peering{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Peering), err
}

// Update takes the representation of a peering and updates it. Returns the server's representation of the peering, and an error, if there is any.
func (c *FakePeerings) Update(ctx context.Context, peering *v1alpha1.Peering, opts v1.UpdateOptions) (result *v1alpha1.Peering, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(peeringsResource, c.ns, peering), &v1alpha1.Peering{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Peering), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePeerings) UpdateStatus(ctx context.Context, peering *v1alpha1.Peering, opts v1.UpdateOptions) (*v1alpha1.Peering, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(peeringsResource, "status", c.ns, peering), &v1alpha1.Peering{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Peering), err
}

// Delete takes name of the peering and deletes it. Returns an error if one occurs.
func (c *FakePeerings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(peeringsResource, c.ns, name), &v1alpha1.Peering{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePeerings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(peeringsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PeeringList{})
	return err
}

// Patch applies the patch and returns the patched peering.
func (c *FakePeerings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Peering, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(peeringsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Peering{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Peering), err
}
