/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-rediscloud-api/apis/rediscloud/v1alpha1"
	scheme "kubeform.dev/provider-rediscloud-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SubscriptionPeeringsGetter has a method to return a SubscriptionPeeringInterface.
// A group's client should implement this interface.
type SubscriptionPeeringsGetter interface {
	SubscriptionPeerings(namespace string) SubscriptionPeeringInterface
}

// SubscriptionPeeringInterface has methods to work with SubscriptionPeering resources.
type SubscriptionPeeringInterface interface {
	Create(ctx context.Context, subscriptionPeering *v1alpha1.SubscriptionPeering, opts v1.CreateOptions) (*v1alpha1.SubscriptionPeering, error)
	Update(ctx context.Context, subscriptionPeering *v1alpha1.SubscriptionPeering, opts v1.UpdateOptions) (*v1alpha1.SubscriptionPeering, error)
	UpdateStatus(ctx context.Context, subscriptionPeering *v1alpha1.SubscriptionPeering, opts v1.UpdateOptions) (*v1alpha1.SubscriptionPeering, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SubscriptionPeering, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SubscriptionPeeringList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SubscriptionPeering, err error)
	SubscriptionPeeringExpansion
}

// subscriptionPeerings implements SubscriptionPeeringInterface
type subscriptionPeerings struct {
	client rest.Interface
	ns     string
}

// newSubscriptionPeerings returns a SubscriptionPeerings
func newSubscriptionPeerings(c *RediscloudV1alpha1Client, namespace string) *subscriptionPeerings {
	return &subscriptionPeerings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the subscriptionPeering, and returns the corresponding subscriptionPeering object, and an error if there is any.
func (c *subscriptionPeerings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SubscriptionPeering, err error) {
	result = &v1alpha1.SubscriptionPeering{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("subscriptionpeerings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SubscriptionPeerings that match those selectors.
func (c *subscriptionPeerings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SubscriptionPeeringList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SubscriptionPeeringList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("subscriptionpeerings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested subscriptionPeerings.
func (c *subscriptionPeerings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("subscriptionpeerings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a subscriptionPeering and creates it.  Returns the server's representation of the subscriptionPeering, and an error, if there is any.
func (c *subscriptionPeerings) Create(ctx context.Context, subscriptionPeering *v1alpha1.SubscriptionPeering, opts v1.CreateOptions) (result *v1alpha1.SubscriptionPeering, err error) {
	result = &v1alpha1.SubscriptionPeering{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("subscriptionpeerings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subscriptionPeering).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a subscriptionPeering and updates it. Returns the server's representation of the subscriptionPeering, and an error, if there is any.
func (c *subscriptionPeerings) Update(ctx context.Context, subscriptionPeering *v1alpha1.SubscriptionPeering, opts v1.UpdateOptions) (result *v1alpha1.SubscriptionPeering, err error) {
	result = &v1alpha1.SubscriptionPeering{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("subscriptionpeerings").
		Name(subscriptionPeering.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subscriptionPeering).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *subscriptionPeerings) UpdateStatus(ctx context.Context, subscriptionPeering *v1alpha1.SubscriptionPeering, opts v1.UpdateOptions) (result *v1alpha1.SubscriptionPeering, err error) {
	result = &v1alpha1.SubscriptionPeering{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("subscriptionpeerings").
		Name(subscriptionPeering.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subscriptionPeering).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the subscriptionPeering and deletes it. Returns an error if one occurs.
func (c *subscriptionPeerings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("subscriptionpeerings").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *subscriptionPeerings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("subscriptionpeerings").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched subscriptionPeering.
func (c *subscriptionPeerings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SubscriptionPeering, err error) {
	result = &v1alpha1.SubscriptionPeering{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("subscriptionpeerings").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
